name: Deploy Preview Branch

on:
  pull_request:
  workflow_dispatch:

jobs:
  build_and_preview:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        run: npm install pnpm@7 -g

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_VICE_2EF34 }}"
          projectId: vice-2ef34
          expires: 1d
          channelId: "pr-${{ github.event.number }}-${{ github.event.pull_request.head.ref }}"
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
