name: Unit and E2E Tests

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        run: npm install pnpm@7 -g

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run unit tests
        run: pnpm test:ci

      - name: Run e2e tests
        run: pnpm cypress install --force && pnpm e2e:ci
